# -*- coding: utf-8 -*-
"""array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjQ3oXavv0jqA8ItC1IsQsyrYyjTlAug
"""

import numpy as np
arr=np.array([1,2,3])
print(arr)

arr[2]

arr[2]=5
arr

#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

#checking the shape of the array
print("the shape  is 2 rows and 3 columns:",arr2.shape)

#accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

#array of type string
arr3=np.array(['india','china','usa','mexico'])
print(arr3)

print(arr3[1])

arr=np.arange(1,30,3)
print(arr)

arr=np.linspace(0,10,30)
print(arr)

#array of random values between 0 and 1 in a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

#creating array with given values
print(np.full((5,6),20))

#repeating array elements
arr=[0,1,2]
print(np.repeat(arr,3))

#repeat array number of times
arr=[1,2,3]
print(np.tile(arr,4))

#creating identity matrix with eye
identity_matrix=np.eye(3)
print(identity_matrix)

#creating identity matrix with identity
identity_matrix=np.identity(3)
print(identity_matrix)

#5X5 array between 0 and 1
arr=np.random.rand(5,5)
print(arr)

print(arr2)

#sum along the column
print(np.sum(arr2,axis=0))

#sum along eow
print(np.sum(arr2,axis=1))

#calculating mean,median,sd and vaeience
print(np.mean(arr2))
print(np.median(arr2))
print(np.std(arr2))
print(np.var(arr2))

#sort an array
arr=np.random.rand(5,5)
print(arr)

#sorting along the row
print(np.sort(arr,axis=1))

#appending the elements
arr=np.array([3,4,5,6])
arr1=np.append(arr,8)
arr1

arr2=np.append(arr,[8,9,10])
print(arr2)

#deleting multple elements
arr2=np.array([4,5,6,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

#concatinating
arr1=np.array([[1,2,3,4],[6,7,8,9]])
arr2=np.array([[11,12,13,14],[16,17,18,19]])
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)











